{
 "title": "Confluence",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License Expiration Estimate",
   "type": "timeseries",
   "description": "Максимально неинформативный и некрасивый график, нужный лишь для алертинга.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "confluence_maintenance_expiry_days_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confluence Disk Space Used (98%)",
   "type": "timeseries",
   "description": "192.168.0.36",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"confluence.elcom.local:9100\",job=\"prometheus\"}) / node_filesystem_size_bytes * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Confluence Disk Space Used (95% LongTerm)",
   "type": "timeseries",
   "description": "192.168.0.36",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"confluence\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"confluence\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"confluence\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"confluence\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"confluence\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time / 1 day rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"confluence\"}[1d])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Login/Logout",
   "type": "timeseries",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(confluence_user_login_count[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(confluence_user_logout_count[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Mail Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "confluence_mail_queue_gauge", "legendFormat": "queue" }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(confluence_request_duration_on_path_sum{job=\"confluence\"}[2m])) by (path)) / (sum(rate(confluence_request_duration_on_path_count{job=\"confluence\"}[2m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Attachments",
   "type": "stat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "confluence_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_uptime_gauge{job=\"confluence\"}"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "stat",
   "description": "The total pages",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "confluence_pages_gauge" }
   ]
  },
  {
   "title": "Blog-posts",
   "type": "stat",
   "description": "The total blog-posts",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "confluence_blogposts_gauge" }
   ]
  },
  {
   "title": "Global spaces",
   "type": "stat",
   "description": "The total global spaces",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "confluence_global_spaces_gauge" }
   ]
  },
  {
   "title": "Personal spaces",
   "type": "stat",
   "description": "The total personal spaces",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "confluence_personal_spaces_gauge"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Allowed users",
   "type": "stat",
   "description": "The maximum allowed users",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "confluence_allowed_users_gauge" }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "description": "The current active users",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "confluence_active_users_gauge" }
   ]
  },
  {
   "title": "1-hour sessions",
   "type": "stat",
   "description": "The total 1-hour active sessions",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "confluence_one_hour_active_users_gauge"
    }
   ]
  },
  {
   "title": "Today sessions",
   "type": "stat",
   "description": "The today active sessions",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "confluence_today_active_users_gauge"
    }
   ]
  }
 ]
}