{
 "title": "GitLab Tokens",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "query": {
     "query": "label_values(gitlab_token,token_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gitlab_token", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quantity tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(gitlab_token)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quantity active tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_token{active=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantity expired tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_token{active=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}