{
 "title": "Jira",
 "description": "Shows Jira JVM and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian",
  "Jira"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jira\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jira\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jira\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"jira\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"jira\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Jira Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Update Issues Per Project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jira_issue_update_count_total) by (projectKey)",
     "legendFormat": "{{projectKey}}"
    }
   ]
  },
  {
   "title": "Update Issues Per User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jira_issue_update_count_total) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Login/Logout",
   "type": "timeseries",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jira_user_login_count_total[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(jira_user_logout_count_total[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Dashboards Views",
   "type": "timeseries",
   "description": "Views of all dashboards increases",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jira_dashboard_view_count_total[1h]))"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(jira_request_duration_on_path_sum[2m])) by (path)) / (sum(rate(jira_request_duration_on_path_count[2m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Attachments",
   "type": "stat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_uptime_gauge{job=\"jira\"}"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "description": "The total issues in Jira",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jira_total_issues_gauge" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "All Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jira_all_users_gauge" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jira_active_users_gauge " }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jira_total_sessions_gauge" }
   ]
  },
  {
   "title": "Authorized  Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jira_authorized_sessions_gauge" }
   ]
  }
 ]
}