{
 "title": "GitLab Omnibus",
 "description": "GitLab Omnibus Dashboard (>= 10.3)",
 "tags": [ "GitLab" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(up{job=\"gitlab\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JQ failed jobs for last 30m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_jobs_failed_total[30m])"
    }
   ]
  },
  {
   "title": "Node Disk Free",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{fstype!~\"tmpfs\",instance=~\"orpo-gitlab.elcom.local:9100\"}) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs\",instance=~\"orpo-gitlab.elcom.local:9100\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  1 -\n  avg without (mode,cpu) (\n    rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"orpo-gitlab.elcom.local:9100\"}[$__interval])\n  )\n)"
    }
   ]
  },
  {
   "title": "Node Available Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemAvailable_bytes{instance=~\"orpo-gitlab.elcom.local:9100\"} or\n  (node_memory_MemFree_bytes{instance=~\"orpo-gitlab.elcom.local:9100\"} + node_memory_Buffers_bytes{instance=~\"orpo-gitlab.elcom.local:9100\"} + node_memory_Cached_bytes{instance=~\"orpo-gitlab.elcom.local:9100\"})\n) / node_memory_MemTotal_bytes{instance=~\"orpo-gitlab.elcom.local:9100\"}"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(pg_up{instance=~\"orpo-gitlab.elcom.local:.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Sidekiq Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitlab\",instance=~\"orpo-gitlab.elcom.local:.*\"}[$__interval])\n) "
    }
   ]
  },
  {
   "title": "Sidekiq Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    sidekiq_queue_size{instance=~\"orpo-gitlab.elcom.local:.*\"}[$__interval]\n  )\n)",
     "legendFormat": "Queued"
    }
   ]
  }
 ]
}